name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t us.icr.io/rose/giftwebsite:latest .

    - name: Log in to IBM Cloud Container Registry
      uses: ibm-cloud/setup-ibmcloud@v1
      with:
        ibmcloud-api-key: ${{ secrets.IBM_CLOUD_API_KEY }}

    - name: Push Docker image to IBM Cloud
      run: docker push us.icr.io/rose/giftwebsite:latest

    - name: Deploy to Code Engine
      run: |
        ibmcloud ce project select -n giftlink-frontend
        ibmcloud ce application update --name giftwebsite-frontend --image us.icr.io/rose/giftwebsite:latest
